# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- task: ArtifactoryNuGet@2
  inputs:
    command: 'restore'
    artifactoryService: 'Amith_service'
    targetResolveRepo: 'san-nuget'
    solutionPath: '**/*.sln'
    collectBuildInfo: true
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: 'nuget-example/MyLogger/MyLogger/MyLogger.csproj'
- task: DotNetCoreCLI@2
  inputs:
    command: 'pack'
    packagesToPack: nuget-example/MyLogger/MyLogger/MyLogger.csproj
    includesymbols: true
    versioningScheme: byEnvVar
    versionEnvVar: 'BUILD_BUILDNUMBER'
- task: ArtifactoryDotnetCore@1
  inputs:
    command: 'push'
    artifactoryService: 'Amith_service'
    targetDeployRepo: 'san-nuget'
    pathToNupkg: '*.nupkg'
    collectBuildInfo: true
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'
    includeEnvVars: true
    targetDeployPath: ''
- task: ArtifactoryNuGet@2
  inputs:
    command: 'push'
    artifactoryService: 'Amith_service'
    targetDeployRepo: 'san-nuget'
    pathToNupkg: '*.nupkg'
    collectBuildInfo: true
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'
- task: ArtifactoryPublishBuildInfo@1
  inputs:
    artifactoryService: 'Amith_service'
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'