# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- task: ArtifactoryNpm@2
  inputs:
    command: 'ci'
    artifactoryService: 'jy-service'
    sourceRepo: 'san-npm'
    workingFolder: 'npm-example'
    collectBuildInfo: true
    threads: '1'
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'
- task: Npm@1
  inputs:
    command: 'custom'
    workingDir: 'npm-example'
    customCommand: 'run build -- --prod=true --buildOptimizer=false --aot=false --output-path=./dist/out'

- task: ArtifactoryPublishBuildInfo@1
  inputs:
    artifactoryService: 'jy-service'
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'