# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: ArtifactoryNpm@2
  inputs:
    command: 'install'
    artifactoryService: 'sandy'
    sourceRepo: 'san-npm'
    workingFolder: 'npm-example/'
    collectBuildInfo: true
    threads: '1'
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'
    arguments: '--prefer-offline --audit=false --no-audit --prefix $(System.DefaultWorkingDirectory'

- task: ArtifactoryPublishBuildInfo@1
  inputs:
    artifactoryService: 'sandy'
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'
- task: JFrogBuildScan@1
  inputs:
    xrayConnection: 'sandeepxray'
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'
    allowFailBuild: true
    vuln: false
