image: gradle:latest

before_script:
  # This variable is used to tell Gradle from which repository to download the build-info-extractor.jar. Should be server-id/repo-name
  - JFROG_CLI_EXTRACTORS_REMOTE=$ARTIFACTORY_SERVER_ID/$ARTIFCATORY_REPO

  # Install JFrog CLI
  - curl -fL https://install-cli.jfrog.io | sh
  # Configure Artifactory server
  - jf config add $ARTIFACTORY_SERVER_ID --url=$ARTIFACTORY_URL --user=$ARTIFACTORY_USER --password=$ARTIFACTORY_PASS

  # Configure Gradle, set upload and download repositories
  - jf gradlec --repo-resolve $ARTIFCATORY_REPO --repo-deploy $ARTIFCATORY_REPO

# This job name will be used as the build info repository name in artifactory
gitlab-ci-gradle-build:
  stage: build
  script:
    # Build and upload the JAR to Artifactory
    - jf gradle clean artifactoryPublish -b build.gradle --build-name=$CI_JOB_NAME --build-number=$CI_JOB_ID
    # Collect environment variables for the build
    - jf rt bce $CI_JOB_NAME $CI_JOB_ID
    # Collect VCS details from Git and add them to the build
    - jf rt bag $CI_JOB_NAME $CI_JOB_ID
    # Publish build info
    - jf rt bp $CI_JOB_NAME $CI_JOB_ID
    # Scan with JFrog Xray
    - jf bs $CI_JOB_NAME $CI_JOB_ID
